# Generated by Django 3.2.20 on 2023-09-16 11:01

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Fuel_Type', models.IntegerField()),
                ('VIN', models.CharField(max_length=200)),
                ('NumPlate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(choices=[('Attard', 'Attard'), ('Ħal-Balzan', 'Ħal-Balzan'), ('Il-Bidnija', 'Il-Bidnija'), ('Il-Birgu', 'Il-Birgu'), ('Birkirkara', 'Birkirkara'), ('Birżebbuġa', 'Birżebbuġa'), ('Bormla', 'Bormla'), ('Ħad-Dingli', 'Ħad-Dingli'), ('Il-Fgura', 'Il-Fgura'), ('Il-Furjana', 'Il-Furjana'), ('Ħal Għargħur', 'Ħal Għargħur'), ('Ħal Għaxaq', 'Ħal Għaxaq'), ('Il-Gudja', 'Il-Gudja'), ('Il-Gżira', 'Il-Gżira'), ('Il-Ħamrun', 'Il-Ħamrun'), ('L-Iklin', 'L-Iklin'), ('Il-Kalkara', 'Il-Kalkara'), ('Ħal Kirkop', 'Ħal Kirkop'), ('Ħal Lija', 'Ħal Lija'), ('Ħal Luqa', 'Ħal Luqa'), ('Il-Marsa', 'Il-Marsa'), ('Marsaskala', 'Marsaskala'), ('Marsaxlokk', 'Marsaxlokk'), ('L-Imdina', 'L-Imdina'), ('Il-Mellieħa', 'Il-Mellieħa'), ('L-Imġarr', 'L-Imġarr'), ('Il-Mosta', 'Il-Mosta'), ('L-Imqabba', 'L-Imqabba'), ('L-Imsida', 'L-Imsida'), ('L-Imtarfa', 'L-Imtarfa'), ('In-Naxxar', 'In-Naxxar'), ('Raħal Ġdid', 'Raħal Ġdid'), ('Pembroke', 'Pembroke'), ('Tal-Pietà', 'Tal-Pietà'), ('Ħal Qormi', 'Ħal Qormi'), ('Il-Qrendi', 'Il-Qrendi'), ('Ir-Rabat Malta', 'Ir-Rabat Malta'), ('Ħal Safi', 'Ħal Safi'), ('San Ġwann', 'San Ġwann'), ('Santa Luċija', 'Santa Luċija'), ('Santa Venera', 'Santa Venera'), ('L-Isla', 'L-Isla'), ('Is-Siġġiewi', 'Is-Siġġiewi'), ('Tas-Sliema', 'Tas-Sliema'), ('San Ġiljan', 'San Ġiljan'), ('San Pawl il-Baħar', 'San Pawl il-Baħar'), ('Is-Swieqi', 'Is-Swieqi'), ('Ħal Tarxien', 'Ħal Tarxien'), ('Ta Xbiex', 'Ta Xbiex'), ('Valletta', 'Valletta'), ('Ix-Xgħajra', 'Ix-Xgħajra'), ('Ħaż-Żabbar', 'Ħaż-Żabbar'), ('Ħaż-Żebbuġ', 'Ħaż-Żebbuġ'), ('Iż-Żejtun', 'Iż-Żejtun'), ('Iż-Żurrieq', 'Iż-Żurrieq'), ('Il-Fontana', 'Il-Fontana'), ('Għajnsiele', 'Għajnsiele'), ('L-Għarb', 'L-Għarb'), ('L-Għasri', 'L-Għasri'), ('Ta Kerċem', 'Ta Kerċem'), ('Il-Munxar', 'Il-Munxar'), ('Ix-Xlendi', 'Ix-Xlendi'), ('In-Nadur', 'In-Nadur'), ('Il-Qala', 'Il-Qala'), ('Ir-Raba', 'Ir-Raba'), ('San Lawrenz', 'San Lawrenz'), ('Ta Sannat', 'Ta Sannat'), ('Ix-Xagħra', 'Ix-Xagħra'), ('Ix-Xewkija', 'Ix-Xewkija'), ('Iż-Żebbuġ Gozo', 'Iż-Żebbuġ Gozo'), ('Marsalforn', 'Marsalforn')], max_length=50)),
                ('Mobile', models.CharField(max_length=8)),
                ('Vat_Number', models.CharField(blank=True, max_length=10)),
                ('ID_number', models.CharField(max_length=10, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Location', models.CharField(choices=[('Attard', 'Attard'), ('Ħal-Balzan', 'Ħal-Balzan'), ('Il-Bidnija', 'Il-Bidnija'), ('Il-Birgu', 'Il-Birgu'), ('Birkirkara', 'Birkirkara'), ('Birżebbuġa', 'Birżebbuġa'), ('Bormla', 'Bormla'), ('Ħad-Dingli', 'Ħad-Dingli'), ('Il-Fgura', 'Il-Fgura'), ('Il-Furjana', 'Il-Furjana'), ('Ħal Għargħur', 'Ħal Għargħur'), ('Ħal Għaxaq', 'Ħal Għaxaq'), ('Il-Gudja', 'Il-Gudja'), ('Il-Gżira', 'Il-Gżira'), ('Il-Ħamrun', 'Il-Ħamrun'), ('L-Iklin', 'L-Iklin'), ('Il-Kalkara', 'Il-Kalkara'), ('Ħal Kirkop', 'Ħal Kirkop'), ('Ħal Lija', 'Ħal Lija'), ('Ħal Luqa', 'Ħal Luqa'), ('Il-Marsa', 'Il-Marsa'), ('Marsaskala', 'Marsaskala'), ('Marsaxlokk', 'Marsaxlokk'), ('L-Imdina', 'L-Imdina'), ('Il-Mellieħa', 'Il-Mellieħa'), ('L-Imġarr', 'L-Imġarr'), ('Il-Mosta', 'Il-Mosta'), ('L-Imqabba', 'L-Imqabba'), ('L-Imsida', 'L-Imsida'), ('L-Imtarfa', 'L-Imtarfa'), ('In-Naxxar', 'In-Naxxar'), ('Raħal Ġdid', 'Raħal Ġdid'), ('Pembroke', 'Pembroke'), ('Tal-Pietà', 'Tal-Pietà'), ('Ħal Qormi', 'Ħal Qormi'), ('Il-Qrendi', 'Il-Qrendi'), ('Ir-Rabat Malta', 'Ir-Rabat Malta'), ('Ħal Safi', 'Ħal Safi'), ('San Ġwann', 'San Ġwann'), ('Santa Luċija', 'Santa Luċija'), ('Santa Venera', 'Santa Venera'), ('L-Isla', 'L-Isla'), ('Is-Siġġiewi', 'Is-Siġġiewi'), ('Tas-Sliema', 'Tas-Sliema'), ('San Ġiljan', 'San Ġiljan'), ('San Pawl il-Baħar', 'San Pawl il-Baħar'), ('Is-Swieqi', 'Is-Swieqi'), ('Ħal Tarxien', 'Ħal Tarxien'), ('Ta Xbiex', 'Ta Xbiex'), ('Valletta', 'Valletta'), ('Ix-Xgħajra', 'Ix-Xgħajra'), ('Ħaż-Żabbar', 'Ħaż-Żabbar'), ('Ħaż-Żebbuġ', 'Ħaż-Żebbuġ'), ('Iż-Żejtun', 'Iż-Żejtun'), ('Iż-Żurrieq', 'Iż-Żurrieq'), ('Il-Fontana', 'Il-Fontana'), ('Għajnsiele', 'Għajnsiele'), ('L-Għarb', 'L-Għarb'), ('L-Għasri', 'L-Għasri'), ('Ta Kerċem', 'Ta Kerċem'), ('Il-Munxar', 'Il-Munxar'), ('Ix-Xlendi', 'Ix-Xlendi'), ('In-Nadur', 'In-Nadur'), ('Il-Qala', 'Il-Qala'), ('Ir-Raba', 'Ir-Raba'), ('San Lawrenz', 'San Lawrenz'), ('Ta Sannat', 'Ta Sannat'), ('Ix-Xagħra', 'Ix-Xagħra'), ('Ix-Xewkija', 'Ix-Xewkija'), ('Iż-Żebbuġ Gozo', 'Iż-Żebbuġ Gozo'), ('Marsalforn', 'Marsalforn')], max_length=50)),
                ('Mobile', models.CharField(max_length=8)),
                ('Vat_Number', models.CharField(max_length=10, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.service')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.business')),
            ],
        ),
    ]
