# Generated by Django 3.2.20 on 2023-08-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.CharField(max_length=10, unique=True)),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
