# Generated by Django 3.2.20 on 2023-08-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_Name', models.CharField(max_length=200)),
                ('Business_Name', models.CharField(max_length=200)),
                ('Location', models.CharField(choices=[('Attard', 'Attard'), ('Ħal-Balzan', 'Ħal-Balzan'), ('Il-Bidnija', 'Il-Bidnija'), ('Il-Birgu', 'Il-Birgu'), ('Birkirkara', 'Birkirkara'), ('Birżebbuġa', 'Birżebbuġa'), ('Bormla', 'Bormla'), ('Ħad-Dingli', 'Ħad-Dingli'), ('Il-Fgura', 'Il-Fgura'), ('Il-Furjana', 'Il-Furjana'), ('Ħal Għargħur', 'Ħal Għargħur'), ('Ħal Għaxaq', 'Ħal Għaxaq'), ('Il-Gudja', 'Il-Gudja'), ('Il-Gżira', 'Il-Gżira'), ('Il-Ħamrun', 'Il-Ħamrun'), ('L-Iklin', 'L-Iklin'), ('Il-Kalkara', 'Il-Kalkara'), ('Ħal Kirkop', 'Ħal Kirkop'), ('Ħal Lija', 'Ħal Lija'), ('Ħal Luqa', 'Ħal Luqa'), ('Il-Marsa', 'Il-Marsa'), ('Marsaskala', 'Marsaskala'), ('Marsaxlokk', 'Marsaxlokk'), ('L-Imdina', 'L-Imdina'), ('Il-Mellieħa', 'Il-Mellieħa'), ('L-Imġarr', 'L-Imġarr'), ('Il-Mosta', 'Il-Mosta'), ('L-Imqabba', 'L-Imqabba'), ('L-Imsida', 'L-Imsida'), ('L-Imtarfa', 'L-Imtarfa'), ('In-Naxxar', 'In-Naxxar'), ('Raħal Ġdid', 'Raħal Ġdid'), ('Pembroke', 'Pembroke'), ('Tal-Pietà', 'Tal-Pietà'), ('Ħal Qormi', 'Ħal Qormi'), ('Il-Qrendi', 'Il-Qrendi'), ('Ir-Rabat Malta', 'Ir-Rabat Malta'), ('Ħal Safi', 'Ħal Safi'), ('San Ġwann', 'San Ġwann'), ('Santa Luċija', 'Santa Luċija'), ('Santa Venera', 'Santa Venera'), ('L-Isla', 'L-Isla'), ('Is-Siġġiewi', 'Is-Siġġiewi'), ('Tas-Sliema', 'Tas-Sliema'), ('San Ġiljan', 'San Ġiljan'), ('San Pawl il-Baħar', 'San Pawl il-Baħar'), ('Is-Swieqi', 'Is-Swieqi'), ('Ħal Tarxien', 'Ħal Tarxien'), ('Ta Xbiex', 'Ta Xbiex'), ('Valletta', 'Valletta'), ('Ix-Xgħajra', 'Ix-Xgħajra'), ('Ħaż-Żabbar', 'Ħaż-Żabbar'), ('Ħaż-Żebbuġ', 'Ħaż-Żebbuġ'), ('Iż-Żejtun', 'Iż-Żejtun'), ('Iż-Żurrieq', 'Iż-Żurrieq'), ('Il-Fontana', 'Il-Fontana'), ('Għajnsiele', 'Għajnsiele'), ('L-Għarb', 'L-Għarb'), ('L-Għasri', 'L-Għasri'), ('Ta Kerċem', 'Ta Kerċem'), ('Il-Munxar', 'Il-Munxar'), ('Ix-Xlendi', 'Ix-Xlendi'), ('In-Nadur', 'In-Nadur'), ('Il-Qala', 'Il-Qala'), ('Ir-Raba', 'Ir-Raba'), ('San Lawrenz', 'San Lawrenz'), ('Ta Sannat', 'Ta Sannat'), ('Ix-Xagħra', 'Ix-Xagħra'), ('Ix-Xewkija', 'Ix-Xewkija'), ('Iż-Żebbuġ Gozo', 'Iż-Żebbuġ Gozo'), ('Marsalforn', 'Marsalforn')], max_length=50)),
                ('Mobile', models.CharField(max_length=8)),
                ('Vat_Number', models.IntegerField(max_length=10, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('Service', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Model', models.CharField(max_length=200)),
                ('Fuel_Type', models.IntegerField()),
                ('VIN', models.IntegerField(max_length=200)),
                ('NumPlate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Location', models.CharField(choices=[('Attard', 'Attard'), ('Ħal-Balzan', 'Ħal-Balzan'), ('Il-Bidnija', 'Il-Bidnija'), ('Il-Birgu', 'Il-Birgu'), ('Birkirkara', 'Birkirkara'), ('Birżebbuġa', 'Birżebbuġa'), ('Bormla', 'Bormla'), ('Ħad-Dingli', 'Ħad-Dingli'), ('Il-Fgura', 'Il-Fgura'), ('Il-Furjana', 'Il-Furjana'), ('Ħal Għargħur', 'Ħal Għargħur'), ('Ħal Għaxaq', 'Ħal Għaxaq'), ('Il-Gudja', 'Il-Gudja'), ('Il-Gżira', 'Il-Gżira'), ('Il-Ħamrun', 'Il-Ħamrun'), ('L-Iklin', 'L-Iklin'), ('Il-Kalkara', 'Il-Kalkara'), ('Ħal Kirkop', 'Ħal Kirkop'), ('Ħal Lija', 'Ħal Lija'), ('Ħal Luqa', 'Ħal Luqa'), ('Il-Marsa', 'Il-Marsa'), ('Marsaskala', 'Marsaskala'), ('Marsaxlokk', 'Marsaxlokk'), ('L-Imdina', 'L-Imdina'), ('Il-Mellieħa', 'Il-Mellieħa'), ('L-Imġarr', 'L-Imġarr'), ('Il-Mosta', 'Il-Mosta'), ('L-Imqabba', 'L-Imqabba'), ('L-Imsida', 'L-Imsida'), ('L-Imtarfa', 'L-Imtarfa'), ('In-Naxxar', 'In-Naxxar'), ('Raħal Ġdid', 'Raħal Ġdid'), ('Pembroke', 'Pembroke'), ('Tal-Pietà', 'Tal-Pietà'), ('Ħal Qormi', 'Ħal Qormi'), ('Il-Qrendi', 'Il-Qrendi'), ('Ir-Rabat Malta', 'Ir-Rabat Malta'), ('Ħal Safi', 'Ħal Safi'), ('San Ġwann', 'San Ġwann'), ('Santa Luċija', 'Santa Luċija'), ('Santa Venera', 'Santa Venera'), ('L-Isla', 'L-Isla'), ('Is-Siġġiewi', 'Is-Siġġiewi'), ('Tas-Sliema', 'Tas-Sliema'), ('San Ġiljan', 'San Ġiljan'), ('San Pawl il-Baħar', 'San Pawl il-Baħar'), ('Is-Swieqi', 'Is-Swieqi'), ('Ħal Tarxien', 'Ħal Tarxien'), ('Ta Xbiex', 'Ta Xbiex'), ('Valletta', 'Valletta'), ('Ix-Xgħajra', 'Ix-Xgħajra'), ('Ħaż-Żabbar', 'Ħaż-Żabbar'), ('Ħaż-Żebbuġ', 'Ħaż-Żebbuġ'), ('Iż-Żejtun', 'Iż-Żejtun'), ('Iż-Żurrieq', 'Iż-Żurrieq'), ('Il-Fontana', 'Il-Fontana'), ('Għajnsiele', 'Għajnsiele'), ('L-Għarb', 'L-Għarb'), ('L-Għasri', 'L-Għasri'), ('Ta Kerċem', 'Ta Kerċem'), ('Il-Munxar', 'Il-Munxar'), ('Ix-Xlendi', 'Ix-Xlendi'), ('In-Nadur', 'In-Nadur'), ('Il-Qala', 'Il-Qala'), ('Ir-Raba', 'Ir-Raba'), ('San Lawrenz', 'San Lawrenz'), ('Ta Sannat', 'Ta Sannat'), ('Ix-Xagħra', 'Ix-Xagħra'), ('Ix-Xewkija', 'Ix-Xewkija'), ('Iż-Żebbuġ Gozo', 'Iż-Żebbuġ Gozo'), ('Marsalforn', 'Marsalforn')], max_length=50)),
                ('Mobile', models.CharField(max_length=8)),
                ('Vat_Number', models.CharField(blank=True, max_length=10)),
                ('ID_number', models.CharField(max_length=10, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200)),
                ('Service', models.CharField(max_length=200)),
                ('cars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cardb')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.AddField(
            model_name='bcust',
            name='cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cardb'),
        ),
        migrations.AddField(
            model_name='bcust',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.cust'),
        ),
    ]
