# Generated by Django 3.2.20 on 2023-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230828_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcust',
            name='Vat_Number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cardb',
            name='VIN',
            field=models.CharField(max_length=200),
        ),
    ]
