# Generated by Django 3.2.20 on 2023-08-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230828_1604'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bcust',
            table='store_businesses',
        ),
        migrations.AlterModelTable(
            name='cust',
            table='store_customers',
        ),
    ]
