# Generated by Django 3.2.20 on 2023-09-16 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='deliver_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 16, 11, 34, 34, 110317, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookservice',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
