# Generated by Django 3.2.20 on 2023-09-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230916_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookservice',
            name='service_provider',
        ),
    ]
