# Generated by Django 3.2.20 on 2023-09-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_bookservice_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='acceptation',
            field=models.BooleanField(default=False),
        ),
    ]
