# Generated by Django 3.2.20 on 2023-09-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230916_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='cancelled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
