# Generated by Django 3.2.20 on 2023-09-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bookservice_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Vat_Number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Vat_Number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
