# Generated by Django 3.2.20 on 2023-09-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230921_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Fuel_Type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='diesel', max_length=20),
        ),
    ]
