# Generated by Django 3.2.20 on 2023-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
