# Generated by Django 3.2.20 on 2023-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bookservice_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookservice',
            options={'ordering': ['completed']},
        ),
        migrations.AlterField(
            model_name='bookservice',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
